---
kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: bench-mem
    namespace: benchmark-containers
  spec:
    replicas: 2
    selector:
      name: bench-mem
    template:
      metadata:
        labels:
          name: bench-mem
          app: benchmark-containers
          namespace: benchmark-containers
      spec:
        containers:
        - name: bench-mem
          image: aleozlx/benchmark-containers
          args: ["mem"]

